### ISSUE TITLE
Change SourceList after initialization

### ISSUE THREAD

**Issue by rogiervandenberg** [letsar/flutter_sidekick#1]
Thanks for your great plugin! 🎉 I am trying to build a select-widget with it, based on the `SidekickTeamBuilder`. The `SidekickTeamBuilder` is in its own builder of a Streambuilder (I am using the bloc model for datastreams), so I (thought I) can just easily filter my `initialSourceList`.

But, even though my `initialSourceList` is setup correctly initially, when repainting the `SidekickTeamBuilder` with a new value for `initialSourceList`, it is never updated anymore when I rebuild/paint the widget.

My question: How could I filter the available (sourceList) items, after it is painted on the screen already?

**Comment by letsar** [comment]
Oh I see, I missed to implement `didUpdateWidget`. I'm going to fix this and publish a new version.
