### ISSUE TITLE
Question : How to show only source and then target

### ISSUE THREAD

**Issue by g-balas** [letsar/flutter_sidekick#6]
Hey,

I would like to make a simple animation, showing at the beggining only the source, and at this end only the target (with SideKick widget)

Could you give me some leads on this ?
Do I have to play with the opacity, listening to the animation status ?

Thanks !

**Comment by tomosullivan8** [comment]
Any luck with this? I've been playing around to try and find out. I was trying to add an AnimatedOpacity based on the SideKickController.value but it doesn't appear to work...

**Comment by g-balas** [comment]
@tomosullivan8 I re-think my architecture, building two views based on absolute position with animation + standard hero navigation for some part.
